name: Compile LaTeX to PDF

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: bharat_yadav_resume.tex

      - name: Prepare output directory
        run: |
          mkdir -p output_pdf
          cp bharat_yadav_resume.pdf output_pdf/Bharat_Yadav_Resume.pdf

      - name: Push PDF to the output branch
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: output_pdf
          build_dir: output_pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}